### ISSUE TITLE
Modèle MVC ?

### ISSUE THREAD

**Issue by ET-AD** [TL1-fa17/projet2#11]
Sur ce projet, est-il nécessaire de développer avec un pattern MVC ?

**Comment by florentvitse** [comment]
Le M c'est nos classes et VC C'est la partie graphique.

**Comment by ET-AD** [comment]
VC est géré en grande partie par Slick2D en fait.

**Comment by florentvitse** [comment]
Oui, c'est Slick2D qui gère les événements et la méthode update() aussi par exemple.
Nos modèles (classes) sont le M de MVC ici.

**Comment by ET-AD** [comment]
Je ne suis pas sur que l'on respecte complètement le pattern MVC. 

Toutefois avec Slick2D je pense qu'il vaut mieux continuer comme ça.

Difficile d'avoir une vision globale avec ce nouvel outil.

**Comment by caronpe** [comment]
Je pense qu'on doit rester sur ce concept. Une fois la partie client-serveur de l'autre groupe codé on mettra la partie Model coté serveur et controleur view coté client.
