### ISSUE TITLE
Action attaquer

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#14]
Ajout de l'action attaquer au personnage, aussi bien sur le plan graphique que algorithmique

**Comment by ET-AD** [comment]
Juste pour que tu ne passes pas à côté, dans "mobile" j'ai mis un attribut "attack".

**Comment by florentvitse** [comment]
Tu as avancé PE ? si tu veux réfléchir ensemble pour attaquer ?
J'ai rien à faire en ce moment [chef qui ne reviens pas avant Jeudi ;) ]

**Comment by caronpe** [comment]
Oui oui tkt! j'ai bientôt fini ^^

**Comment by caronpe** [comment]
Si tu veux il y encore bcp de choses à faire ^^ (genre les pièges, la fin du jeu, la page de connexion ,...)

**Comment by caronpe** [comment]
L'attaque fonctionne demain je vais essayer de mettre une animation pour que ça soit plus visible

**Comment by ET-AD** [comment]
action attaquer j'avais pensé à un projectile plutôt qu'une attaque au corps à corps. Qu'en pensez vous ? J'ai du mal à imaginer le gameplay de combats corps à corps versus cpu...

**Comment by florentvitse** [comment]
Pas mal je viens de tester l'attaque là, ça marche du tonnerre et le code propre et simple, tout comme il faut ! :D
Pour l'animation de l'attaque pour l'instant, ce serait bien de d'afficher ce genre d'image à la place du monstre quand on appuie sur espace et ça revient après sur le monstre tant qu'il est pas mort ;)

https://0.s3.envato.com/files/265236.jpg

**Comment by caronpe** [comment]
oui je pensais aussi à une petite explosion sur le montre lors ce qu'il se fait toucher ^^ je vais chercher ça!
Pour le type d'attaque on peut tenter plusieurs armes différentes (épée, pistolet, rayon laser,...) mais ça sera pour de futures version.
