### ISSUE TITLE
Erreur de location de fonction

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#23]
Aprés avoir regardé plus largement le code je pense que beaucoup de fonctions sont situées au mauvais endroit!
dans Windows game:
- move() à passer dans Mobile
- collision() , isExit(), findExit() à déplacer dans Map

La class windowsGame doit uniquement servir de partie Controleur, View.

**Comment by florentvitse** [comment]
Fait, dites-moi si une chose est encore mal placée ?

**Comment by caronpe** [comment]
à premiére vu c'est good!

**Comment by caronpe** [comment]
Je ferme et on reouvrira si on détécte d'autres problémes ^^
