### ISSUE TITLE
Pixel ou case?

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#24]
Peut on m'expliquer si pour faire tourner notre programme on travaille avec des pixels ou des cases de tableau? On augmente l’attribut abscisse du joueur en pixel mais on fait nos tests sur les cases  et si je me trompe pas les déplacements sont aussi de case en case.

Voilà, si une âme charitable peut me fournir une explication ;-)

**Comment by florentvitse** [comment]
Je vais t'expliquer, moi aussi je m'y perds parfois.

Le placement du joueur est représenté par x et y en PIXEL, comme tu l'as compris, on le déplace de PIXEL en PIXEL jusqu'à arriver au coordonnées d'une case (origine = en haut à gauche)

Par contre quand tu veux savoir si la prochaine tuile est une collision par exemple, c'est par rapport aux CASES du quadrillage qui forme la map [on affiche pas le calque de collision mais on recherche dedans]

PS : Pour les exits j'ai codé sur ce principe également :)

**Comment by florentvitse** [comment]
La méthode getTileId prend en arguments des int je crois 0:0 représente la première case en haut à gauche.
1:0 celle à sa droite
0:1 celle en dessous
