### ISSUE TITLE
Mobile extends Object (Obstacle)

### ISSUE THREAD

**Issue by ET-AD** [TL1-fa17/projet2#26]
Histoire que vous ne soyez pas surpris.

Le code de Object (anciennement : Obstacle) se retrouve pratiquement entièrement et de manière identique dans Mobile.

J'ai repensé la structure UML.
D'un point de vue "Objet", un joueur est un objet mobile et non franchissable.

J'ai fait les modifications nécessaires.

**Comment by caronpe** [comment]
Attention je suis pas sûre d avoir bien compris!  Il ne doit pas y avoir deux fois le même code dans un programme (ssinon problème de conception).
Si tu comptes faire hériter joueur de obstacle Why not mais dans ce cas il faut changer le nom "obstacle" par quelque chose de plus parlant ("élément" par exemple)

**Comment by caronpe** [comment]
Dans ce cas les classes héritieres seraient "décors ""piège" ... en gros tout ce qui se pose sur la carte

**Comment by ET-AD** [comment]
Oui le problème était que le code se retrouvait à l'identique. J'ai factorisé tout ça notamment avec un "Mobile extends Objetc".

J'ai renommé Obstacle en Object. En partant du principe que Joueur est un objet sur la carte (tu peux changer en "Element" si tu préfères).

"en gros tout ce qui se pose sur la carte"
Voila, tout ce qui se pose sur la carte est objet selon notre nouveau modèle ou plutôt selon notre manière de coder.

J'espère avoir été plus clair cette-fois ci. 
Je pense avoir compris la même chose que toi, PE.

**Comment by florentvitse** [comment]
ATTENTION : La classe Object existe déjà en Java est d'ailleurs tous les objets (classe) héritent implicitement de celle-ci.

Je viens de puller tes derniers commits et j'ai des erreurs partout @e-adriansen !!!
Je n'ai pas la classe Object dans le projet !

EDIT : Refresh d'ECLIPSE à la con - never mind !

**Comment by ET-AD** [comment]
Effectivement je n'ai pas pensé à la classe Object de base.

Je viens de renommer "Object" en "Element".

PS : Je test le code avant de push Flo ;)

**Comment by cdlm** [comment]
PS à propos du refresh Eclipse: il y avait des BOM Unicode dans 2-3 fichiers que j'ai dû enlever avec un éditeur hexa parce que `javac` ne les gère pas… quelqu'un a dû éditer le code avec un autre éditeur ?
