### ISSUE TITLE
Affichage de la vie et force d'attaque

### ISSUE THREAD

**Issue by florentvitse** [TL1-fa17/projet2#29]
Affichage des levels de vie et de force sous forme de barre progressives/dégressives en haut à gauche de l'écran.

**Comment by florentvitse** [comment]
J'essaie en ce moment de rechercher comment afficher la vie, l'arme sélectionnée par exemple, j'ai trouvé ce style là pour l'instant
![hud fight](https://cloud.githubusercontent.com/assets/9799077/6480878/adac09dc-c258-11e4-94b1-3c371b789be1.png)

Est-ce que cela est bien où on préférerait un autre truc, je suis ouvert aux propositions :)

**Comment by florentvitse** [comment]
Soit je peux copier ces barres de PV à l'ancienne 

![image](https://cloud.githubusercontent.com/assets/9799077/6481216/f1f2cde4-c25b-11e4-80b1-9845d4bd9fa7.png)

**Comment by florentvitse** [comment]
Voilà un aperçu avec la deuxième solution style pokémon, je trouve que ça correspond avec la charte graphique nan ? :)

![sans titre 1](https://cloud.githubusercontent.com/assets/9799077/6487059/4b4f7d1e-c28f-11e4-8bb8-896268292acd.jpg)
![sans titre 2](https://cloud.githubusercontent.com/assets/9799077/6487058/4b4d3cb6-c28f-11e4-8f95-06280cc40d75.jpg)

Si cela vous va, je passe au codage.

**Comment by caronpe** [comment]
Personnellement je suis fan du style! Comme tu l'as proposé sur #28 on va mettre un boolean qui empéche le personnage en combat de quitter la carte tant que le montre est pas vaincu

**Comment by florentvitse** [comment]
Ok ça marche je fais comme ça alors
Je réflechis où implémenter l'objet HUD vu que c'est de la vue mais ses données dépendent d'autres objets, still thinking !

**Comment by caronpe** [comment]
N'hesites pas à créer des objets, ça ségmente le code et le rend plus lisible! 
Hier j'ai créé dans ma branche l'objet "AnimationAttaque" qui contiendra toutes les animations liées aux attaques.
Comme ça dans windows game il suffira de faire:
draw(AnimationAttaque.hit , ....)

toute la partie création d'animation est donc invisible dans la class VC.

(ces modifs ne sont pas encore push donc tu ne les verra pas sur github)

**Comment by ET-AD** [comment]
+1 pour le design des barres de vie et l'idée d’empêcher la sortie du combat avec un rocher.

L'apparition d'un rocher temporaire permet de créer une sorte d'arène de combat (limite espace de déplacement). Je suis pour!

**Comment by florentvitse** [comment]
J'ai fait un peu de Photofiltre et j'affiche également la force d'attaque, barre en dessous de la vie pour le joueur, c'est bien comme ça que vous le voyiez aussi ?
Je vais maintenant m'attaquer à afficher la barre du monstre quand on est en combat, j'attends un peu donc que vous ayez avancez pour que ce soir plus simple pour moi ;)

**Comment by florentvitse** [comment]
Affichage de la Vie du monstre est fonctionnel, j'attends pour voir comment obtenir la vie du monstre quand le player est en combat pour l'afficher (en gros je suis en attente)
Je vais me consacrer au bug des portes en attendant.
