### ISSUE TITLE
Création d'attaque des PNJ

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#30]

**Comment by caronpe** [comment]
e-Adriensen:

Je suis sur l'animation d'attaque PNJ. J'ai supposé monsterOne est un FireLord (extends PNJ)
son attaque projète des boules de feu (Fireball extends Element) qui au contactent avec le joueur explosent et blessent le joueur.

Je rencontre des soucis avec les boules de feu.
Je m'y prends peut être mal mais actuellement c'est Firelord qui créé Fireball et cela me pose quelques soucis en particuliers :

```
tester déplacement (collision solid/joueur) de la fireball. Les collisions étant gérées par map (et je trouve cela cohérent mais je ne me vois pas passer la map en argument...)
isOnEdge implémenté directement sur KeyPressed(xxx)
Autre problème secondaire : Fireball actuellement extends Element car Mobile n'est pas Crossable (facilement corrigable mais je ne veux pas impacter le reste du code pour le moment)
```

Avant d'aller plus loin et de faire des modifications qui impacteraient d'autres parties du code, j'aimerais votre avis sur comment gérer le déplacement de la boule de feu proprement.
De l'aide ne serait pas de trop.

```
SHA: 470d950
```

PS : j'ai rajouté les diagonales à Direction, pour que boule de feu puisse se déplacer en diagonale.

**Comment by caronpe** [comment]
L'idée est cool mais il va faloir la décomposer je pense!

Pour ce qui est des déplacements je pense que pour le moment ça sera plus sage de pas mettre les diagonal pour ne pas complexifier trop rapidement! 

Pour l'objet mobile non crossable je pense que c'est effectivement une erreur de logique de notre part (ça vaut peut etre le coup de créer une issue "bug")

Pour la gestion des collision et du mouvement j'ai crée getNearPosition() dans mobile, en regardant comment j'ai codé la fonction attaque ça peut être interressant de recréer une fonction (qui pourrait remplacer notre précédente gestion des collisions).

**Comment by caronpe** [comment]
Parcontre pour le déplacement de la boule de feu je sais pas comment la faire bouger. J'ai actuellement un "probléme" sur ce point avec les animations liées aux attaques. Je sais pas si l'utilisation de Thread est une bonne solution?

**Comment by ET-AD** [comment]
J'essaie de repenser ça ce soir. Peut être voir aussi avec florent vu qu'il a codé et pensé la gestion maps/sorties/adversaires.

La sur le coup je pense que le soucis vient que ce n'est pas la map qui créé le projectile. Peut être faire en sorte que Firelord lance un appel à map pour créer un nouvel adversaire projectile...? Je regarde ça ce soir.

Peut être même que l'on devrait créer une classe abstraite projectile vu qu'elle pourrait être reprise par PNJ et joueur ?

**Comment by ET-AD** [comment]
Je pense avoir trouvé une solution. 
Il me reste à : 
- gérer les collisions de Fireball
- créer un déplacement automatique pour Firelord

PS : la disposition des maps actuellement n'est pas vraiment adaptée pour les combats tel que je les imagine (Firelord ça passe encore, mais pour d'autres idées cela devient problématique => manque d'espace).
Les maps sont telles définitives ? cela pose-t-il un problème de modifier leur structure ? Il faut dire qu'au départ PE avait proposé qu'on oriente les salles comme "the binding of isaac". Je pense qu'on peut adapter des PNJ aux maps actuelles mais le gameplay sera moins fun.
Je pense qu'il serait bien de faire le point la dessus ensemble.

**Comment by caronpe** [comment]
Je suis d'accord avec toi ça va manquer de fun!
Limite je propose un fonctionnement comme Pokemon: 
En gros tu vois le monstre sur la map (le monstre immobile comme actuellement), tu donnes un coup d'épée. ça transporte les deux personnages sur une arène (type binding of isaac) avec combat en temps réel. Une fois le monstre tué la voie est dégagé.
Je pense que ça peut rendre le code beaucoup plus digeste que actuellement de séparer dans une arène les combats.

**Comment by florentvitse** [comment]
Oui Étienne ça serait beau et tout de faire des trucs comme ça mais c'est long à mettre en place et le but de notre projet, c'est de découvrir le travail en équipe et tout donc c'est déjà pas mal ce qu'on arrive à faire surtout qu'on est pas à plein temps dessus.

Pour le fait de déporter le combat dans une arène, je suis pour et contre en même temps. Moi je voyais bien que l'on attaque les monstres directement sur la Map, chacun son tour, on perd de la vie avec les monstres et on en regagne en récoltant des items et il y aurait genre - Il faut battre le monstre la avant celui-la sinon on aura pas assez de vie, enfaite élaborer un scénario de jeu.
[Pour que ça fasse beau, chaque monstre a son attaque, les bulles d'eau, des flammes etc contre nous]

Après pour déporter le combat, il y a un tuto pour cumuler les fenetres comme vous l'avez décris dans le lien du README. À voir mais ça rajoute beaucoup de graphique par la suite et d'expérience, c'est chiant et long pour faire des fois pas grand chose :)

**Comment by ET-AD** [comment]
@florentvitse Je ne proposais rien de précis. Juste l'idée de revoir cela ensemble.

J'aime beaucoup l'idée de PE, comme ça cela nous permet de garder nos maps actuelles qui sont plutôt jolies. Et permet d'avoir un gameplay sûrement plus amusant.

@florentvitse pourquoi cumuler les fenêtres ? utiliser le même système qu'actuellement (rajouter des maps/téléporteurs) n'est pas possible ? Un téléporteur utilisable qu'une seule fois et hop, FIGHT ! :3 puis si monstre vaincu reviens sur coordonnées X,Y de map n°X

**Comment by florentvitse** [comment]
Oui tu peux faire ça aussi, le changement de MAP pour le combat.

**Comment by ET-AD** [comment]
C'est cool que tu y jettes un coup d’œil car je suis en difficulté pour poursuivre ! Un coup de main de serait pas de trop ! ;)

Pour en revenir sur ton commentaire IC (InCode), tu as tout à fait raison, je mettais trompé et j'ai corrigé mais peut être pas comme tu le penses, laisse moi d'abord t'expliquer ce que j'ai voulu faire :

Je voulais que lorsque Player entre dans la map (ou entre dans zone de combat) Firelord s'active : 
- lance des boules de feu => j'entends pas là créé un projectile qui se déplace dans une direction unique (verticalement, horizontalement (par la suite en diagonale)) et se détruise au premier contact (joueur/mur/...) toutes les X secondes.
- et Firelord se téléporte à chaque coup par exemple mais on verra ça après selon la map etc...
  
  Je suis pour l'instant sur la création de Fireball et son déplacement automatique ...une ligne droite.
  SignumAbsciss et SignumOrdinate permet de donner la direction à Fireball par rapport à la position actuelle de Firelord et de celle du Joueur.

Fireball ball = new Fireball(fireballPosition, this.scale, signumAbsciss, signumOrdinate, getAttack(), 1, map);

**Comment by florentvitse** [comment]
Oui je comprends le concept complet je pense mais comme l'avais dit PE, segmente toutes ces choses en en faisant petit à petit.
Là les différentes étapes seraient :
- Détection quand le joueur rentre sur la Map en question
- Lancer une boule de feu, en ligne droite, par exemple par le bas de la position du monstre(encore immobile) sans gérer les obstacles. [Elle traverse tous]
- Gérer la collision de LA boule avec l'environnement
- Lancer plusieurs boules, faire 2 puis 3 puis 4 boules pour atteindre les 4 directions [les diagonales ne sont pas nécessaires à mon avis et rajouteront beaucoup de complexité]
- Gérer la collision avec le joueur.
- Diminuer la vie du joueur.

Voilà comment à mon avis, ta partie devraient s'orienter pour que tu avances progressivement mais surement et bien sûr, écriture des tests "avant" le codage.

EDIT : Il faut résoudre le bug (Issue #32 ) avant de commencer tous ça aussi je pense sinon regarde, premier point, tu risques p-e d'avoir déjà des problèmes !

**Comment by ET-AD** [comment]
Ok je vais faire ça car je t'avoues que j'ai essayé de le faire d'un coup et le seul résultat que j'ai obtenu c'est Crash Error...

Je suis revenu sur la dernière partie fonctionnelle et je reprends de là.

EDIT : Oui tu as complètement raison priorité au bug téléporteurs

**Comment by florentvitse** [comment]
Au vu du temps qu'il nous reste, je lance une question, va-t-on vraiment réaliser les combats sur une autre carte déportée ou alors directement sur la Map où est le monstre en question, je penche plus pour la seconde solution moi car la première fais imaginer beaucoup de nouvelles choses (ce qui prend du temps) et aussi, PE a déjà commencé l'animation du player sur la Map (qui est plutôt réussi), ne resterai plus qu'à faire de même pour le monstre. Sachant aussi qu'il faut encore prévoir la fin du jeu...

**Comment by caronpe** [comment]
Coucou,  désolé de pas avoir bcp programmé la semaine dernière j étais sur un gros projet. Je dois encore finir les animations d attaque ( juste du photo montage à faire). Pour ta proposition je suis d accord! De toute façon il faut développer par petite amélioration. Si on a le temps on créera l arène sinon pas grave ^^

**Comment by florentvitse** [comment]
Oui pareil j'ai regardé par petite touche et là j'attaque une reprise de TMA complète donc je peux aider mais pas autant qu'au début ^^ et pour les anims je vais essayer de faire un result potable pour l'attaque avec autre qu'une épée si je trouve une idée PE, je te proposerais ;)

**Comment by ET-AD** [comment]
Ok priorité anime attaque PNJ semblable à celle du joueur actuellement.

**Comment by ET-AD** [comment]
J'ai fait une attaque automatique PNJ à chaque attaque du joueur. 
RSA: 292dd149a8fdad0d069f665099990706a92b9eac

Il manque l'animation. Je ne suis pas expert photoshop. 
Faut il : 
- une animation du PNJ en train d'attaquer 

ou 
- une boule de feu.png (déjà existant) par dessus l'image du joueur suffit ?

EDIT : en y repensant il serait mieux de faire une animation sur le PNJ plutôt que cumuler les images sur le joueur.

**Comment by florentvitse** [comment]
D'abord la logique, on attaque, le joueur se met en combat, on ne peut plus bouger, on attaque, le pnj attaque jusqu'a ce que l'un des 2 meurent, decrementation des points etc fonctionnelles, on voit apres pour les animations 😉

**Comment by ET-AD** [comment]
Si j'ai bien compris, tu veux que je rajoute le fait que le joueur ne puisse plus bouger une fois le combat commencé, c'est bien ça ?

**Comment by florentvitse** [comment]
Oui on n'avait pensé comme ça avec PE & l'attribut isMobile existe déjà dans la classe.

**Comment by e-adriansen** [comment]
Ok je m'occupe de ça cet aprem.

**Comment by ET-AD** [comment]
Ok je m'occupe de ça cet aprem.

EDIT :
En fait c'est plutôt la partie Player de PE quand j'y pense. 
Peut être mieux que je le laisse faire, j'essaie de ne plus déborder sur vos parties.

**Comment by ET-AD** [comment]
J'ai créé une première arène. Si l'on a pas le temps de finir j'annule le commit. c'est bien ça ?

EDIT : Ou c'est peut être trop tôt ? finir d'abord la version statique ?
PS : version statique il manque juste animation (visuel) PNJ et bloquer le Joueur...

EDIT 2 : J'annule mon commit le temps que l'on en discute.

**Comment by caronpe** [comment]
Tu peux modifier  ce que j'ai écris mon code ne  m appartient pas. Il faut juste pas effectuer la même tâche que moi au même moment ^^ . Donc fais toi plaisir ;-) 
Pour l arène soir tu as fini l attaque des pnj et dans ce cas tu ferme cette issue et tu en crée une  nouvelle soir je te conseille de finaliser tout  travail avant de te lancer dans une  nouveau gros morceau

**Comment by caronpe** [comment]
(Fhievevjfjkdicejdhcdodg de  t9 de m****)

**Comment by caronpe** [comment]
Bon je vais créer plusieur Issues parceque celle-ci devient trop grosse et c'est impossible à gérer.

**Comment by florentvitse** [comment]
Le personnage est vraiment petit à mon goût, c'est temporaire où ?

**Comment by caronpe** [comment]
(Pas la bonne issue) on va essayer de laisser celle ci uniquement pour les attaques pnj sinon on avancera pas sur ce point.

**Comment by caronpe** [comment]
Je prend la décision de fermer cette Issue car elle nous bloque dans le développement du jeu. Elle est bien trop large et abandonné par tous! On va redécouper ça sur #13
