### ISSUE TITLE
Build failing et zéro tests !

### ISSUE THREAD

**Issue by cdlm** [TL1-fa17/projet2#31]
Scrogneugneu :angry:

**Comment by florentvitse** [comment]
Je vais essayer de rédiger le plus de tests possible ce soir.
Est-il nécessaire de tester les getteurs/setteurs simples, je ne pense pas ?

**Comment by ET-AD** [comment]
"Build fail" J'imagine que cela correspond au point d'interrogation rouge sur le dossier du projet (dans eclipse). Cela n'empêche pas l'execution du programme, qu'est-ce que cela signifie?

D'où peut provenir le "Build fail" ?
Je l'ai aperçu pour la première fois vendredi soir il me semble, donc je pense à un commit du vendredi ou jeudi. Quelqu'un l'a-t-il aperçu avant ?

EDIT : j'ai fait pas mal de "reverts" et je n'ai pas réussi à enlever ce build failing... peut être un conflit lors d'un merge, est-ce possible ?

**Comment by caronpe** [comment]
Je suis le dernier à avoir commit vendredi ça vient peut être de moi :-( ...

**Comment by caronpe** [comment]
Qq à une petite définition "build failing"?

**Comment by florentvitse** [comment]
Le "build failling" vient simplement des tests je pense, ils ne sont pas implémentés et JUnit a généré des itérations de fail dans chaque test comme ça, il faut les résoudre pour passer.

**Comment by cdlm** [comment]
Exactement. Tous vos tests font un bête `fail()`… on fait plus utile comme test :)
Pour le build c'est la compilation + tests, que ça soit dans Eclipse ou [sur Travis](https://travis-ci.org/TL1-fa17/projet2).
