### ISSUE TITLE
téléporteurs fonctionnent mal

### ISSUE THREAD

**Issue by ET-AD** [TL1-fa17/projet2#32]
- Impossible d'aller sur la 4ème map
- puis lorsque l'on veut revenir en arrière les téléporteurs envoient le Joueur sur les mauvaises portes.

Je suis sur le coup

**Comment by florentvitse** [comment]
J'ai testé ce midi et il n'y avait aucun problèmes, quel sont les portes qui posent problèmes. 
Réponds moi comme ça :

Map X - Endroit de la porte VERS Map Y

**Comment by ET-AD** [comment]
Une image sera plus parlant...

![bug1](https://cloud.githubusercontent.com/assets/10976583/6557945/43474cc6-c679-11e4-9213-7484e8bae152.png)

**Comment by ET-AD** [comment]
Comme tu peux le voir, la téléportation ne s’enclenche pas.

Cette image correspond à : 
- Impossible d'aller sur la 4ème map

**Comment by ET-AD** [comment]
![21](https://cloud.githubusercontent.com/assets/10976583/6558147/87160694-c67a-11e4-8c14-bfa4b9983b04.png)

![22](https://cloud.githubusercontent.com/assets/10976583/6558138/728778d4-c67a-11e4-89e6-f8ace5af576f.png)

**Comment by ET-AD** [comment]
Exemple pour : 
- puis lorsque l'on veut revenir en arrière les téléporteurs envoient le Joueur sur les mauvaises portes.

PS : il y a plusieurs portes dans ce cas

**Comment by ET-AD** [comment]
Ce peut-il que le problème soit lié au build failing reporté #31 ?

**Comment by ET-AD** [comment]
Il manquait une exit à fourthMap, mais cela ne résous pas les bugs.

**Comment by florentvitse** [comment]
Aucune Exit présente sur la fourthMap était voulu, je n'en avais pas mis justement dans une logique de jeu.
Pour ce qui est du passage de la troisième à la quatrième, cela fonctionnait quand je l'ai re-testé au travail ce matin et cela fonctionne encore chez moi.
Je vois que tu en as rajouté une et maintenant il y a un bug oui car tu te "téléportes" mais tu rentres dans une collision, de la troisième vers la 4, tu vas vers le haut ou par la gauche pour passer, ce qui te fait avancer et finalement des fois tu te retrouves sur le calque de collision, d'où le bug...
Pareillement, de la quatre vers la 3.

@e-adriansen - Cette fonctionnalité, comme c'est moi qui l'ai codé, tu n'aurais pas du la modifier toi même et créer seulement cette issue 'bug' en expliquant le problème, on ne va pas s'en sortir si tout le monde touche aux parties des autres, en voici un exemple.
Je connais cette partie, c'est moi qui fait les modifs comme tu les ferai sur une des tienne si je trouve un bug :)

**Comment by cdlm** [comment]
Commentaire en passant, c'est pas forcément une bonne idée de revendiquer la propriété de telle ou telle partie du code. Imaginez ce que ça donne en extrapolant : si chaque développeur est expert sur sa partie et seulement cette partie, personne d'autre ne sait comment corriger un problème dessus. Le jour où cette personne part, le projet a perdu toute expertise sur le code concerné.

Donc il vaut mieux passer du temps à prendre le temps de communiquer, à s'assurer que le correctif de bug est correct et que c'est le bon moment pour l'appliquer, que les mainteneurs concernés sont au courant, etc. Voir en particulier [cette discussion](http://martinfowler.com/bliki/CodeOwnership.html)

**Comment by florentvitse** [comment]
Je ne dis pas qu'il ne faut pas comprendre le code des autres, mais en parler avant de modifier.
Je suis d'accord je meurs demain, le projet continue sa vie quoi.

**Comment by ET-AD** [comment]
Citation : "Il manquait une exit à fourthMap, mais cela ne résous pas les bugs."
J'en ai parlé lol ^^ ok j'attends pas la réponse ... :p mais maintenant je créé les issues lol patience je m'améliore ! ;)

Par contre peut être tu aurais pu parler avant de "Aucune Exit présente sur la fourthMap était voulu, je n'en avais pas mis justement dans une logique de jeu." ...
si tu pouvais développer stp ;) Je ne saisie pas la logique de jeu.

Si je respecte "ta partie", laisse moi décider de l'état de mon issue xD 
Dire le bug n'existe pas "j'en ai pas chez moi" ce n'est pas régler le problème, car il y en a bien un de mon côté ;) Peut être un problème semblable à la vitesse de déplacement qui diffèrait selon PC ?

Je vais essayer d'être plus explicite sur le bug rencontré : 
4 maps : n°0 , 1 , 2 , 3
- Impossibilité d'aller sur la map n°3 => téléporteur map n° 1 vers n° 3 ne fonctionne jamais (avant ou après mes modifs).
- après avoir essayé d'aller sur la map n°3 => je prends le chemin en sens inverse. Et cette fois ci plus aucun teleporteur ne fonctionne correctement. Exemple les deux screen dans un seul comment ci dessus. => téléporteur map n° 1 sortie n°3 vers map n° 1 vers sortie n°4

Depuis mon PC perso cela fonctionne (épée comprise SHA: 6a32d3a6c631bfaf3fc1c13d4f948f989baa5373 ) , mais pas depuis mon PC boulot... cela me rapelle l'histoire du déplacement.... mais à l'envers cette fois ! Je regarderais de nouveau demain...
PE as tu des soucis avec les téléporteurs toi aussi ? (je pense que non car j'ai l'impression que le bon fonctionnement de animations attaques et téléporteurs sont liés ><)

**Comment by florentvitse** [comment]
Avec tes screens, je vois que tu travailles sur une ancienne version car tu n'as pas les barres en bas.
Je viens de constater le bug aussi, il ne survient pas au premier passage chez moi mais à "l'usure", à force de les utiliser.
Je regarderais ça ce soir si j'ai le temps, c'est peut-être dans la classe Position ou Exit ou dans la déclaration de celles-ci car c'est bien les coordonnées d'arrivées qui ne sont pas bonnes mais le déplacement du personnage est effectif.

**Comment by ET-AD** [comment]
En fait les barres en bas font partie des problèmes qui ne s'affichent pas... maintenant que j'y pense on dirait que les modifications en ligne ne sont plus pris en compte... Est-ce un hasard ? ou est-ce parce que se sont des modifications graphiques ? Le problème du déplacement n'est pas graphique... je ne comprends pas. 
Le git pull me dit que je suis à jour et j'ai bien l'historique des derniers commits !

**Comment by florentvitse** [comment]
La barre du joueur en bas doit être apparente, ça c'est sur.
Le problème de déplacement non n'est pas graphique car tu changes bien de position et/ou de map sauf que ce n'est pas les bon ordre ou des trucs comme ça...

Pour savoir si tu es à jour, il y a deux lignes de commentaires à la fin de la méthode render dans la classe WindowGame, elles proviennent de mon dernier commit et donc ça te diras si tu es à jour, sinon tu suppr et tu reclones (expérience déjà vécue)

**Comment by ET-AD** [comment]
// RECUPERATION DE LA VIE DU MONSTRE QUE L'ON EST EN TRAIN DE COMBATTRE
//displayHUDMonsters(g, 50);

J'ai bien les deux lignes de commandes ci-dessus dans mon projet Eclipse. Suis-je le seul à avoir ce problème @caronpe @cdlm ?

**Comment by florentvitse** [comment]
Oui c'est celles-ci donc tu devrais voir la vie du joueur s'affiché en bas à gauche normalement.
Regarde, je viens de le lancer maintenant, j'ai enlevé le texte aussi dans le dernier commit.

![image](https://cloud.githubusercontent.com/assets/9799077/6573484/819356c6-c71b-11e4-8f04-f2bb5e4138bf.png)

**Comment by ET-AD** [comment]
lol Je n'ai pu le texte " 2015 GameZ..." dans le code mais il apparaît toujours à l’exécution...

**Comment by caronpe** [comment]
Je n ai pas encore testé je te dis ça à 16h.  Sinon vérifies que tu as bien opengl sur ton pc (maj peut être nécessaire).
Regardes également si ta fenêtre a bien la même résolution que la fenêtre normal de jeu (en théorie oui)
Fais un gît status pour verifier que tu as pas de modification (parfois un caractère se glisse sans se rendre compte)

**Comment by cdlm** [comment]
Est-ce que vous pensez à faire "refresh (F5)" voire Project>Clean après chaque utilisation de git?

Vu ce que vous dites, on dirait que vous n'exécutez pas le bytecode correspondant au source Java, je n'irais pas chercher bien plus loin.

**Comment by ET-AD** [comment]
Je fais F5 à chaque pull. J'ai testé le Project>Clean rien n'y faisait.
J'ai décidé de supprimer et recharger l'ensemble et cela fonctionne correctement de nouveau.
Citation @florentvitse  "sinon tu suppr et tu reclones (expérience déjà vécue)" :+1: 

Pour en revenir sur le bug des téléporteurs, maintenant je te rejoins florent, il ne reste que le problème lié à "l'usure"

**Comment by florentvitse** [comment]
Il faut résoudre ce bug avant de commencer autre chose Étienne sinon ça va se cumuler ensuite...

**Comment by ET-AD** [comment]
Ok tu as raison.

**Comment by florentvitse** [comment]
Regarde si c'est justement la classe Position avec le nouveau equals qui était pas au point, ça peut p-e fonctionnait normalement maintenant, je fais le test et je reviens vers toi.

EDIT : Il y est toujours.

**Comment by ET-AD** [comment]
Confirme moi que c'est aussi ok de ton côté flo

RSA: b878eb1262d787bf2a1d46c579b02fe8de076dab

**Comment by florentvitse** [comment]
Ça fonctionne, 3 tests différents de parcours et l'usure n'affecte plus le changement oui.
Ça fait du bien de plus l'avoir celui-là !
