### ISSUE TITLE
Pourquoi LinkedList exit / adversaries sur Map.java

### ISSUE THREAD

**Issue by ET-AD** [TL1-fa17/projet2#34]
Petite question : pourquoi utilise-t-on spécifiquement des LinkedList alors que l'on n'utilise pas les propriétés propres aux LinkedList ? 

Je pensais l'avoir modifié mais j'ai du faire mon back up entre temps, je préfère poser la question avant de modifier de nouveau.

Map.java

//paramètres de classe
private List<Exit> exit;
private List<PNJ> adversaries;

//constructor
this.exit = new LinkedList<Exit>();
this.adversaries = new LinkedList<PNJ>();

**Comment by florentvitse** [comment]
De quelle propriété propre parles-tu ?
LinkedList<T> est préférable à ArrayList<T> quand on ne fait que parcourir les éléments, l'Array... est préféré quand on fait de multiples insertions/suppressions.

Le prof l'avait expliqué en télégroupe il me semble.

**Comment by cdlm** [comment]
@florentvitse c'est l'inverse, `LinkedList` est meilleur pour les insertions/suppressions, `ArrayList` pour les accès par indices.

Il me semble avoir vu qu'originalement les variables étaient typées `LinkedList` au lieu de `List`. En tout cas c'est comme ça que je comprends la question de @e-adriansen: le type statique devant être le type nécessaire et suffisant pour écrire le code utilisateur de la variable, `List` suffit mais `LinkedList` sur-contraindrait le choix d'implémentation fait dans le constructeur.

**Comment by florentvitse** [comment]
Ah je croyais que LinkedList s’apparentait à une liste chainée et que c'était plus facile de la parcourir (car finalement nous, dans notre programme, on ne fais que la parcourir du début à la fin sans se soucier des indices mais je ne pense pas que pour stocker 3-4 objets, il n'y ai de différence au niveau du temps d’exécution)

**Comment by cdlm** [comment]
Dans les deux cas c'est la même boucle, donc ce n'est ni plus facile ni plus difficile… la différence est dans la complexité des opérations et dans la localité en mémoire, mais comme vous dites ça n'est probablement pas visible sur des collections de moins de 10 éléments.
