### ISSUE TITLE
Création de bonus de vie

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#35]

**Comment by caronpe** [comment]
Il ne manque plus que l'affichage sous la forme d'un gros coeur

**Comment by florentvitse** [comment]
Je viens de regarder ton code et la classe Trigger, elle ne devraient pas être plutôt une interface vu qu'elle n'implémente pas de nouveaux attributs mais juste la méthode action() ?

**Comment by florentvitse** [comment]
Je cherchais des images de coeur pour toi et je me suis aperçu qu'enfaite, une image style de potion serait bien mieux ? Qu'est ce que tu en penses ?

https://www.google.fr/search?q=potion+png+32&espv=2&biw=1920&bih=979&tbm=isch&source=lnt&tbs=isz:ex,iszw:32,iszh:32

Notamment, cella là  : http://shotbow.net/forum/images/health_potion.png

**Comment by ET-AD** [comment]
J'ai apporté quelques modifications pour afficher du texte et reprendre la classe Item

RSA: 5d034b93086a3aee79ddc2f40f4e45e4724a7b34

**Comment by ET-AD** [comment]
C'est dommage que lorsque le texte s'affiche ça cache la barre de vie.
Le must aurait été de voir la barre de vie augmenter et pour ça peut être centrer le texte comme proposé @florentvitse 
#46 

C'est du chipotage, car perso je suis super content du rendu.

**Comment by caronpe** [comment]
Oublies pas de déclarer des modification AVANT de les faire. (Au passage l'affichage du texte est cool ;-)  )
Pour l'affichage de la barre de vie c'est effectivement du chipotage même si je préfère personnellement voir la vie augmenter dans la barre que voir le texte s'afficher...

**Comment by caronpe** [comment]
Par contre je suis vraiment pas convaincu de l'utilité de la class Item (voir ma remarque sur ton commit).

**Comment by caronpe** [comment]
Je ferme cette Issue car les Bonus de vie sont "fini" rouvrir une issue en cas de modification.
