### ISSUE TITLE
Fins du jeu

### ISSUE THREAD

**Issue by florentvitse** [TL1-fa17/projet2#36]
- Quand on meurt, affichage d'un écran noir avec un message et affichage d'un résumé de la progression ? [Car je sens que ça va être dur de relancer le jeu de zéro sans recompilation]
- Si on a tous combattu, on arrive à la fin de la quatrième carte et on est félicité par un écran de crédit avec nos noms.

**Comment by caronpe** [comment]
je suis d'accord avec le concept! Par contre de quelle compilation parles tu?

**Comment by florentvitse** [comment]
Je voulais kill le process pour le relancer lol mais ça ne sera pas cette solution finalement je pense :)

**Comment by caronpe** [comment]
Non c'est un peu bourrin. (petite précision, quand tu relances le programme tu n'effectues pas la compilation mais l'exécution du programme. Sous éclipse la compilation s'effectue au fur et à mesure de l'écriture du programme. Je sais pas si c'était une erreur de vocabulaire donc je précise ^^)

**Comment by florentvitse** [comment]
Pour proposer l'option "Re-jouer" direct sans quitter le programme, il faut faire une méthode de remise à zéro de tous ce qui a pu être modifié (attributs, monstres) <=> 'refaire' la méthode init() de la classe MapGameState est appeler celle-ci pour la première fois dans l'init() et quand on veut réessayer.

Est-ce que l'on implémente cette possibilité ? @caronpe @e-adriansen

**Comment by e-adriansen** [comment]
Cela posera un problème avec le changement d'indexMap par PNJ

**Comment by ET-AD** [comment]
Pourquoi ne le ferait on pas ?

J'ai lu ton message ce matin en vitesse (mon temps Telecom est l'après midi) et j'ai cru que tu demandais de l'aide. J'ai codé une version qui fonctionne. Ce que j'ai fait semble être exactement ce que tu décris et cela fonctionne parfaitement.

Je ne comprends pas ce qui te fais hésiter. @florentvitse 
PS : je ne push pas si tu as déjà développé une version qui fonctionne

**Comment by caronpe** [comment]
si c'est facile ne te prive pas ;-) . Je pense qu'il suffirait de suppr les suppr le contenu de nos variables dans MapGameState et de refaire tourner la fonction init non?

**Comment by florentvitse** [comment]
J'ai relu ton code @e-adriansen et j'ai corrigé car tu as mélangé plusieurs concept je pense.
(Regarde les 2-3 avant-avant-derniers commit, tu peux me poser des questions si tu ne comprends pas)

Note : J'avais fait l'accès à la fin par une touche, tu aurais du laisser comme c'était et en choisir une autre comme je l'ai fait dans mon dernier commit pushé ;) - 2 touches pour tester deux choses en attendant de bien les implémenter.

**Comment by ET-AD** [comment]
@caronpe On ne peut pas refaire tourner la fonction init(). Elle ne peut être appelée qu'une seule fois (propriété de slick2D). La solution étant de transférer le contenu de notre fonction init() dans une méthode de RemiseAZero() appelée une fois dans la fonction init() puis plus tard dans le jeu pour revenir à l'état du début.

@florentvitse Effectivement j'ai mélangé plusieurs concepts, désolé my bad ;)

**Comment by florentvitse** [comment]
J'ai effectué les dernières modifs sur l'écran de fin, celui-ci est désormais terminé, je ferme l'issue.
