### ISSUE TITLE
Création d'un de l'entrée et sortie d'Arêne 

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#39]
Création de l'entrée d'arêne suite à l'attaque du PNJ, sortie à la mort du PNJ

**Comment by caronpe** [comment]
Et suppr de son cadavre lors de la sortie

**Comment by ET-AD** [comment]
J'ai du mal à suivre, je pensais que j'avais fait  #38 #39 lors du RSA: aab5ba5486af1ce83f5c20613412f19dd4166c82

**Comment by ET-AD** [comment]
Ok c'est du refactoring (désolé y a beaucoup de commits et d'issues en peu de temps en ce moment).

Précise refactoring dans tes commits, c'est plus simple pour relire ensuite car y a tellement de commits d'un coup lol

**Comment by ET-AD** [comment]
Je ne suis pas sur que cela doit être PNJ qui déclenche le changement de map. J'avais à terme imaginé les triggers dans Map un peu comme Exit (et même regrouper Exit et trigger car une Exit est un trigger selon moi).

Mais on n'a peut être pu vraiment le temps pour tout ça. C'est pas faux ce que tu as fait loin de là, mais je l'avais imaginé autrement.

**Comment by caronpe** [comment]
J'ai changé pour que le personnage déclenche le combat en tapant sur le PNJ, c'est plus sympa que de se faire téléporter en passant devant et surtout plus facile à gérer dans la déclaration des trigger pour aller dans l’arène.
En effet chaque PNJ se charge de t’emmener dans l’arène avec lui, et de te ramener à sa position une fois mort.

Pour les Trigger-Exit j'ai fait cette modification jeudi.
