### ISSUE TITLE
GROS CHANGEMENT

### ISSUE THREAD

**Issue by florentvitse** [TL1-fa17/projet2#40]
Application du Tutoriel 15

![](http://i.imgur.com/RxCMWCg.jpg)

**Comment by florentvitse** [comment]
Comme vous pouvez le voir sur la photo, voici la nouvelle archi que je vais devoir mettre en place pour mettre en place une 'FIN' donc comme c'est facile, je vais essayer de rien casser pour mettre en place la fin et ensemble après ça serait bien d'appliquer le modèle pour votre arène si VRAIMENT on a le temps 😉

**Comment by caronpe** [comment]
Bah vu ce que j'ai fait hier tu peux ne pas séparer l arène et les map tout fonctionne sans pB!

**Comment by florentvitse** [comment]
C'est bien ce que je pensais puis vu qu'on a pas le temps, avez-vous touché à l'affichage des HUDs vu que maintenant il ne doivent apparaître que dans l’arène ?
Si non, je vais m'en occuper également.

**Comment by caronpe** [comment]
Tu peux me dire ce qu est un hud?  J ail vu ça dans le code mais j ai pas regardé précisément

**Comment by florentvitse** [comment]
Le HUD c'est l'affichage de la vie (les barres en bas) je viens de tester le code et non il n'est plus pris en charge à voir.

**Comment by caronpe** [comment]
Haaaaaaaa oui dsl j avais oublié. 
Pour la vie je suis pas sûre qu il soit plus pris en charge. J ai juste suppr l attaque du pnj à chaque attaque du joueur (sinon je me faisais kill contre les mobs :-(  )

**Comment by florentvitse** [comment]
Pas grave, je le remettrai juste quand la carte 'arène' est en marche, normalement comme les deux méthodes prennent en argument soit le joueur, soit le monstre (à mettre dans une seule méthode d'ailleurs (I'll see this later)) vous n'avez pas à vous souciez de l'affichage, juste à bien gérer leurs points de vie.

**Comment by florentvitse** [comment]
JE VIENS D'APPLIQUER LE GROS CHANGEMENT, PULLER BIEN avant de continuer vos développements.

**Comment by cdlm** [comment]
HEIN? AH PARDON J'AI CRU RECONNAÎTRE UNE VOIX FAMILIÈRE…
![RIP Sir Pratchett](http://upload.wikimedia.org/wikipedia/en/b/b9/Death_Discworld.png)

**Comment by florentvitse** [comment]
???

**Comment by caronpe** [comment]
#trololo ^^
Le virage a été négocié sans trop de problème ;-)

**Comment by florentvitse** [comment]
C'est bon c'est tout bon, on effectue le changement de state avec la touche '8' du clavier numérique, vous pouvez tester.
Je ferme l'issue
