### ISSUE TITLE
BUG Arène

### ISSUE THREAD

**Issue by florentvitse** [TL1-fa17/projet2#41]
Je viens de tester l'attaque dans une arène et j'y est trouvé un bug, explication du comportement, quand on appuie sur ESPACE et que l'on veut combattre (devant un monstre), quand l'arène s'affiche (la première fois ça va le bug n'est pas présent) mais les autres fois, l'arène s'affiche et l'animation sur le monstre survient rapidement alors que l'on est encore loin de celui-ci.

**Comment by caronpe** [comment]
Yes j avais aussi détecté le bug mais j ai oublié de le corriger  je fais ça de suite
