### ISSUE TITLE
Taille des personnages

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#42]
J'ai crée le sprite sheet pour des personnages de 40x50 px. je peux le redimentionner et le faire grandir si vous préférez ^^

**Comment by florentvitse** [comment]
Moi je le verrais bien comme avant en tout cas il faudrait pour la 'beauté' du jeu qu'il soit de taille 32_32 car cela correspond aux casses ainsi le déplacement reste lisse comme avant de la case de départ à la case d'arrivée.
Après libre à toi de jouer avec la transparence, juste qu'il soit centré sur un carré 32_32 :)

**Comment by caronpe** [comment]
Je suis d'accord! je pensais que le rendu serait meilleur que ça. je vais redimensionner de suite.

**Comment by caronpe** [comment]
Redimensionnement effectué donnez moi vos avis!

**Comment by florentvitse** [comment]
Ça me va presque bien :p je chipote mais reste du blanc autour du personnage (pourquoi pas le garder quand il prend un bonus style aura du joueur ^^) et j'ai comme une vague impression qu'il est légèrement étiré sur la hauteur mais sinon bon boulot !

**Comment by florentvitse** [comment]
Dans la classe AnimationView,

animation.draw(player.getPosition().getAbsciss() - 15, player.getPosition().getOrdinate() -22);

Ces valeurs en dur, 15 et 22 correpondent à quoi ?

**Comment by caronpe** [comment]
C'est la différence de taille entre la taille d une tuile et la taille d une case dans le Sprite sheet (ça centre le personnage sur sa case)

**Comment by florentvitse** [comment]
Okay :)
