### ISSUE TITLE
passage map1-2

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#43]
Depuis moins d'une semaine le passage à la map 2 est très long lors du premier franchissement. Une explication?

**Comment by florentvitse** [comment]
C'est le chargement de la seconde musique qui prend ce temps là, si on la désactive ça fonctionne bien, d'ailleurs on devrait pas arriver sur la sortie mais juste une case devant si tu pouvais faire le changement :)

**Comment by caronpe** [comment]
music.setBackgroundMusic(map.get(indexMap).getMusicFilename());

**Comment by florentvitse** [comment]
Voilà beaucoup d'appels de fonction

**Comment by florentvitse** [comment]
Pour la musique, on réglera ça à la fin, vu que maintenant il y a plusieurs "états" il faut que je repense p-e l'implémentation, bref !
