### ISSUE TITLE
Objet Déclencheur

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#44]
Je vais mettre en place les bonus de vie (et surement les pièges au passage). 
Je suis pas super convaincu du fonctionnement de nos Exits actuelles, au final elles ne sont là que pour stocker des positions mais elles n'effectuent pas la sortie elle même.

Ma proposition est donc d'appliquer ce qu'on a vu au cours de jeudi en affectant une liste d'objet déclencheur dans la map. (ces objets pouvant être des sorties, des pièges, des bonus, ...). Si les position correspondent à celle du joueur on fait appelle à leur fonction trigger() et celle-ci applique l'actions qui leurs correspondent.

Ceci fera un grand ménage dans le code et je trouve que ça sera plus logique.

**Comment by florentvitse** [comment]
Tout a fait d'accord, dès que tu as trouvé la solution, (si tu peux avant de coder sinon ce n'est pas grave) l'expliquer car ça m'intéresse beaucoup ce pattern 😉

**Comment by florentvitse** [comment]
Car sinon on peut créer une interface et redéfinir les méthodes qui porteront le même nom à chaque fois et profiter de l'exécution retardée de Java 😉

**Comment by caronpe** [comment]
Bah c'est codé maintenant ^^ (dsl je suis en forme ces derniers jours...)
Tu as bien deviné,
J'ai crée une class abstraite Trigger héritant de Element,
celle ci contient une fonction abstraite action().
Je réutilise le code déjà codé en plaçant des trigger à la place des Exit. sachant que j'appelle dessus sa fonction action() (peu importe si c'est un bonus ou une Exit elle fait son travail tranquillement)
