### ISSUE TITLE
Affichage de bulles de texte

### ISSUE THREAD

**Issue by florentvitse** [TL1-fa17/projet2#46]

**Comment by florentvitse** [comment]
J'ai fait l'affichage des info-bulles qui rend pas mal je trouve, je dois juste trouver la solution pour bien les afficher, j'ai encore un petit bug là-dessus mais sinon donnez-moi votre avis.

Et petite question, vous voudriez que l'affichage soit centré si la phrase n'est pas aussi longue que l'exemple ou c'est l'info-bulles qui devrait être réduite ?

**Comment by florentvitse** [comment]
J'ai amélioré l'affichage du texte avec un affichage lettre par lettre comme si on écrivait la phrase en direct, ça rend 'extra' je trouve donc faudrait vraiment l'utiliser dans les phases du jeu que vous codées.

**Comment by ET-AD** [comment]
Rendu vraiment sympa !
