### ISSUE TITLE
Player trop grand quand regarde vers le bas

### ISSUE THREAD

**Issue by ET-AD** [TL1-fa17/projet2#48]
J'imagine qu'il suffit de réduire l'image. 
Si je me trompe et que c'est trop compliqué, ce n'est pas grave, c'est du détail.

![image](https://cloud.githubusercontent.com/assets/10976583/6806077/ee6cc328-d246-11e4-8b58-a4957b4d4163.png)

**Comment by caronpe** [comment]
c'est pas super compliqué mais ça prendra du temps. Je te fait ça avant la fin du projet ;-)
