### ISSUE TITLE
Création de Bonus et piéges

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#49]

**Comment by ET-AD** [comment]
Pour les pièges j'avais l'idée de faire une case en feu => herbe du jeu mais rouge (à voir le rendu).
Crossable : lorsque le joueur passe dessus -5 pv par exemple.
Juste une idée comme ça.

**Comment by caronpe** [comment]
Bah je vais tenter un truc plus beau avec un animation (genre les plantes carnivores dans mario)

**Comment by florentvitse** [comment]
Allez comme ça on aura du décor pokémon, le player Link et des plantes Mario - Interculturalité + 10 :+1:

**Comment by florentvitse** [comment]
J'ai trouvé ça, ils ont l'air cool - WARN : la transparence n'existe pas sur les images.

![dracofeu](https://cloud.githubusercontent.com/assets/9799077/6843663/5703d7dc-d3a5-11e4-83f8-fb7f502c00f9.png)
![carnivore](https://cloud.githubusercontent.com/assets/9799077/6843664/5707def4-d3a5-11e4-9a5e-2277e764cfb8.png)

**Comment by caronpe** [comment]
J ai déjà une anim stylé.  J attend juste de régler un pb d algorithmes avant de push
(Mon pb actuel est que j essaye de supprimer le piège de la liste que je  parcoure en même temps)

**Comment by florentvitse** [comment]
AH d'accord petit pb oui lol

**Comment by florentvitse** [comment]
Une solution possible, stockage de l'index et un remove() derrière à la fin du parcours ;)

**Comment by caronpe** [comment]
Pas stupide du tout!  Je vais tester ça cette après midi

**Comment by florentvitse** [comment]
Carrément arrêter la boucle quand tu l'as trouvé (break) puis supprimer l'élément 'i' si tu as utilisé une variable d'itération est une possibilité également ;)
